kind: Service
apiVersion: v1
metadata:
  name: kubernetes-configmap-reload
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap-reload
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap-reload
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
        - name: kubernetes-configmap-reload
          image: praveensingam1994/kubernetes-configmap-reload:latest
