kind: Service
apiVersion: v1
metadata:
  name: kubernetes-configmap-reload
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap-reload
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
